# Interface to listen on
interface eth0

# Start and end of IP lease block
start 192.168.100.50
end 192.168.100.150

# Lease time in seconds
opt lease 43200

# Gateway
opt router 192.168.100.1

# DNS server
opt dns 192.168.100.1

# Subnet mask
opt subnet 255.255.255.0

# Location of PID file
pidfile /var/run/udhcpd.pid

# Location of leases file
lease_file /var/lib/misc/udhcpd.leases
