name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - "main" # For upstreaming
      - "senpai" # My own development
jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Check free space
        run: df -h
        
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
        
      - name: Check free space
        run: df -h
     
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Cache rootfs build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
            build/
          key: rootfs-${{ hashFiles('rootfs.sh', 'packages/**') }}
          restore-keys: |
            rootfs-
      
      - name: build rootfs
        run: sudo ./rootfs.sh
      
      - name: upload rootfs
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-alpine
          path: output/rootfs-alpine.tar.gz
  
  build-system:
    strategy:
      matrix:
        # device: [ pico-mini-b, pico-plus, pico-pro-max ]
        device: [ pico-plus ]
    runs-on: ubuntu-latest
    needs: build-rootfs
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          submodules: "recursive"
      
      - name: ccache setup
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
      
      - name: download rootfs
        uses: actions/download-artifact@v5
        with:
          name: rootfs-alpine
          
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: apt-${{ runner.os }}-${{ hashFiles('.github/workflows/main.yml') }}
          restore-keys: |
            apt-${{ runner.os }}-
      
      - name: update apt
        run: sudo apt update
      
      - name: install deps
        run: "sudo apt install -y \
          git ssh make gcc gcc-multilib g++-multilib \
          module-assistant expect g++ gawk texinfo libssl-dev \
          bison flex fakeroot cmake unzip gperf autoconf \
          device-tree-compiler libncurses5-dev pkg-config bc \
          python-is-python3 passwd openssl openssh-server \
          openssh-client vim file cpio rsync"
      
      - name: Cache buildroot downloads
        uses: actions/cache@v4
        with:
          path: |
            sdk/dl
            sdk/build_dir
          key: buildroot-${{ matrix.device }}-${{ hashFiles('sdk/**') }}
          restore-keys: |
            buildroot-${{ matrix.device }}-
            buildroot-
      
      - name: build system
        run: ./system.sh -f rootfs-alpine.tar.gz -d ${{ matrix.device }}
      
      # - name: upload update.img
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.device }}-sysupgrade
      #     path: output/${{ matrix.device }}-sysupgrade.img
      
      - name: upload sdk images
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}-outputs
          path: sdk/output/image
